name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Install kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: 'v1.29.0'
      id: install
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: zon-coffee
        IMAGE_TAG: latest
      run: |
        docker build --file ./Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    - name: Pull Helm Package from AWS ECR Repo
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_HELM_REPOSITORY: zon-coffee-helm
      run: |
        helm pull oci://$ECR_REGISTRY/$ECR_HELM_REPOSITORY
    - name: Update kube config
      run: aws eks update-kubeconfig --name my-cluster --region ${{ secrets.AWS_REGION }}
    - name: Deploy helm package to EKS
      run: |
        helm install zon-coffee ./zon-coffee-helm-0.1.0.tgz
    
